name: Create Deploy Comment
description: Creates and Updates the deploy Comment
inputs:
  deploy-url:
    description: Url for deployed preview
    required: true
runs:
  using: composite
  steps:
    - name: Find Comment
      uses: peter-evans/find-comment@v2
      id: 'fc'
      with:
        issue-number: ${{ github.event.pull_request.number }}
        comment-author: 'github-actions[bot]'
        body-includes: '# :rocket: Preview Deploy Report'

    - name: Create Comment
      if: steps.fc.outputs.comment-id == ''
      uses: peter-evans/create-or-update-comment@v2
      with:
        issue-number: ${{ github.event.pull_request.number }}
        body: |
          # :rocket: Preview Deploy Report

          ✅ Successfully deployed preview [here](${{ inputs.deploy-url }})

    - name: Update Comment
      if: steps.fc.outputs.comment-id != ''
      uses: peter-evans/create-or-update-comment@v2
      with:
        comment-id: ${{steps.fc.outputs.comment-id}}
        edit-mode: replace
        body: |
          # :rocket: Preview Deploy Report Updated

          ✅ Successfully deployed preview [here](${{ inputs.deploy-url }})
