generatorName: typescript-angular
# https://github.com/OpenAPITools/openapi-generator/blob/master/docs/generators/typescript-angular.md
additionalProperties:
  apiModulePrefix: Ccf
  configurationPrefix: CcfApi
  fileNaming: kebab-case
  ngVersion: "12.1.1"
  npmName: "@ccf-openapi/ng-client"
  stringEnums: true
  supportsES6: true
  useSingleRequestParameter: true
