generatorName: typescript-angular
templateDir: projects/ccf-openapi/templates/angular-client
# https://github.com/OpenAPITools/openapi-generator/blob/master/docs/generators/typescript-angular.md
additionalProperties:
  apiModulePrefix: Ccf
  configurationPrefix: CcfApi
  fileNaming: kebab-case
  ngVersion: "16.1.5"
  npmName: "@ccf-openapi/ng-client"
  stringEnums: true
  supportsES6: true
  useSingleRequestParameter: true
