generatorName: typescript-fetch
# https://github.com/OpenAPITools/openapi-generator/blob/master/docs/generators/typescript-fetch.md
additionalProperties:
  # TODO add npmName
  supportsES6: true
  useSingleRequestParameter: true
