generatorName: typescript-fetch
# https://github.com/OpenAPITools/openapi-generator/blob/master/docs/generators/typescript-fetch.md
additionalProperties:
  npmName: "@ccf-openapi/ts-client"
  supportsES6: true
  useSingleRequestParameter: true
